# Generated by Django 4.2.7 on 2024-07-04 15:45

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_id], verbose_name='username')),
                ('password', models.CharField(max_length=255, validators=[accounts.validators.validate_password], verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh_token')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[accounts.validators.validate_phone], verbose_name='phone')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='name')),
                ('content', models.TextField(verbose_name='name')),
                ('is_necessary', models.BooleanField(default=True, verbose_name='is_necessary')),
            ],
            options={
                'verbose_name': '개인정보 이용약관',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, verbose_name='type_name')),
            ],
        ),
        migrations.CreateModel(
            name='TACAgree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consent', models.CharField(choices=[('True', '동의'), ('False', '비동의')], max_length=5, verbose_name='is_consent')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='consent_date')),
                ('tac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '약관 동의',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_name], verbose_name='name')),
                ('gender', models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN')], max_length=1, verbose_name='gender')),
                ('birth', models.DateField(verbose_name='birth')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, validators=[accounts.validators.validate_phone], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype')),
            ],
            options={
                'verbose_name': '회원정보',
            },
        ),
    ]
