# Generated by Django 4.2.7 on 2024-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('W', 'WOMAN'), ('M', 'MAN')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(choices=[('Self', '본인'), ('Guard', '보호자')], max_length=10, verbose_name='user_type'),
        ),
    ]
