# Generated by Django 4.2.7 on 2024-08-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='name')),
                ('content', models.TextField(verbose_name='name')),
                ('is_necessary', models.BooleanField(default=True, verbose_name='is_necessary')),
            ],
            options={
                'verbose_name': '개인정보 이용약관',
            },
        ),
        migrations.AlterField(
            model_name='tacagree',
            name='is_consent',
            field=models.CharField(choices=[('True', '동의'), ('False', '비동의')], max_length=5, verbose_name='is_consent'),
        ),
        migrations.CreateModel(
            name='UserTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consent', models.CharField(choices=[('True', '동의'), ('False', '비동의')], max_length=5, verbose_name='is_consent')),
                ('consent_date', models.DateField(auto_now_add=True, verbose_name='consent_date')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '약관 동의',
            },
        ),
    ]
