# Generated by Django 4.2.7 on 2024-06-26 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGradeEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '비회원 요양등급평가',
                'verbose_name_plural': '비회원 요양등급평가그룹',
            },
        ),
        migrations.CreateModel(
            name='CareGradeSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급간소평가',
                'verbose_name_plural': '요양등급간소평가 그룹',
            },
        ),
        migrations.CreateModel(
            name='CareGradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급세부평가',
                'verbose_name_plural': '요양등급세부평가 그룹',
            },
        ),
    ]
