# Generated by Django 4.2.7 on 2025-05-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGradeEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='등급평가 데이터')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('region', models.CharField(blank=True, max_length=10, null=True, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '비회원 요양등급평가',
                'verbose_name_plural': '비회원 요양등급평가 목록',
                'db_table': 'caregrade_ex',
            },
        ),
        migrations.CreateModel(
            name='GovService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=128, verbose_name='서비스 ID')),
                ('name', models.CharField(max_length=256, verbose_name='서비스명')),
                ('purpose', models.TextField(verbose_name='서비스 목적')),
                ('category', models.CharField(max_length=128, verbose_name='서비스 분야')),
                ('has_region', models.BooleanField(default=False, verbose_name='지역제한')),
                ('region', models.CharField(blank=True, max_length=128, null=True, verbose_name='지역명')),
                ('region_detail', models.CharField(blank=True, max_length=128, null=True, verbose_name='지역 상세명')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='마감기한')),
                ('organization_name', models.CharField(max_length=128, verbose_name='소관기관명')),
                ('organization_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='전화번호')),
                ('description', models.TextField(verbose_name='지원내용')),
                ('target_audience', models.TextField(verbose_name='지원대상')),
                ('age_limit', models.IntegerField(blank=True, null=True, verbose_name='나이제한')),
                ('detail_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='상세조회URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정부 서비스',
                'verbose_name_plural': '정부 서비스 목록',
                'db_table': 'gov_service',
            },
        ),
        migrations.CreateModel(
            name='CareGradeSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='등급평가 데이터')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('region', models.CharField(blank=True, max_length=10, null=True, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급 간소평가',
                'verbose_name_plural': '요양등급 간소평가 목록',
                'db_table': 'caregrade_simple',
            },
        ),
        migrations.CreateModel(
            name='CareGradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='등급평가 데이터')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('region', models.CharField(blank=True, max_length=10, null=True, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급 세부평가',
                'verbose_name_plural': '요양등급 세부평가 목록',
                'db_table': 'caregrade_detail',
            },
        ),
    ]
