# Generated by Django 4.2.7 on 2025-01-03 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGradeEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('region', models.CharField(blank=True, choices=[('JNM', '전라남도'), ('USN', '울산광역시'), ('GWN', '강원특별자치도'), ('CNM', '충청남도'), ('SEO', '서울특별시'), ('SEJ', '세종특별자치시'), ('GNG', '경기도'), ('GJU', '광주광역시'), ('GNM', '경상남도'), ('DJN', '대전광역시'), ('JBK', '전북특별자치도'), ('CBK', '충청북도'), ('DGU', '대구광역시'), ('ICN', '인천광역시'), ('GBK', '경상북도'), ('JJU', '제주특별자치도'), ('BSN', '부산광역시')], max_length=10, null=True, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '비회원 요양등급평가',
                'verbose_name_plural': '비회원 요양등급평가그룹',
            },
        ),
        migrations.CreateModel(
            name='CareGradeSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('region', models.CharField(blank=True, choices=[('JNM', '전라남도'), ('USN', '울산광역시'), ('GWN', '강원특별자치도'), ('CNM', '충청남도'), ('SEO', '서울특별시'), ('SEJ', '세종특별자치시'), ('GNG', '경기도'), ('GJU', '광주광역시'), ('GNM', '경상남도'), ('DJN', '대전광역시'), ('JBK', '전북특별자치도'), ('CBK', '충청북도'), ('DGU', '대구광역시'), ('ICN', '인천광역시'), ('GBK', '경상북도'), ('JJU', '제주특별자치도'), ('BSN', '부산광역시')], max_length=10, null=True, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급간소평가',
                'verbose_name_plural': '요양등급간소평가 그룹',
            },
        ),
        migrations.CreateModel(
            name='CareGradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('region', models.CharField(blank=True, choices=[('JNM', '전라남도'), ('USN', '울산광역시'), ('GWN', '강원특별자치도'), ('CNM', '충청남도'), ('SEO', '서울특별시'), ('SEJ', '세종특별자치시'), ('GNG', '경기도'), ('GJU', '광주광역시'), ('GNM', '경상남도'), ('DJN', '대전광역시'), ('JBK', '전북특별자치도'), ('CBK', '충청북도'), ('DGU', '대구광역시'), ('ICN', '인천광역시'), ('GBK', '경상북도'), ('JJU', '제주특별자치도'), ('BSN', '부산광역시')], max_length=10, null=True, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요양등급세부평가',
                'verbose_name_plural': '요양등급세부평가 그룹',
            },
        ),
    ]
