# Generated by Django 4.2.7 on 2024-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregradedetail',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='caregradeex',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='caregradesimple',
            name='gender',
            field=models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1, verbose_name='gender'),
        ),
    ]
