# Generated by Django 4.2.7 on 2024-10-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_category_options_remove_comments_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlikes',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='author',
            new_name='user',
        ),
    ]
